### ISSUE TITLE
Improper naming: "measurement", not "measurment"

### ISSUE THREAD

**Issue by vvhitesmoke** [Mondonno/Airly.Net#2]
Hi,
there is a mistake in naming: term "measurment" is invalid, should be "measurement" (the difference is an 'e' character).

**Comment by Mondonno** [comment]
Hello @vvhitesmoke

Thank you for finding this mistake.
I will fix it in the next few commits. If it will be fixed I will close this thread.

**Comment by Mondonno** [comment]
Fixed in 839fd31fcc3d3389cc7fdaf50440023768907773
